// <auto-generated />
using System;
using BookingApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingApp.Migrations
{
    [DbContext(typeof(OfficeDbContext))]
    [Migration("20221205155014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingApp.Models.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 4, 23, 0, 0, 0, DateTimeKind.Utc),
                            SeatId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Name = "Lille Grensen"
                        });
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            Name = "Storerommet",
                            OfficeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 5,
                            Name = "Lillerommet",
                            OfficeId = 1
                        });
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Seat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "01",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "02",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "03",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "04",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "05",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "06",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "07",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "01",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "01",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "10",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "11",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "12",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "13",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "14",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "15",
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("BookingApp.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ted.mosby@himym.com",
                            Name = "Ted Mosby",
                            PhoneNumber = "00000001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marshall.eriksen@himym.com",
                            Name = "Marshall Eriksen",
                            PhoneNumber = "00000002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lily.aldrin@himym.com",
                            Name = "Lily Aldrin",
                            PhoneNumber = "00000003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "barney.stinson@himym.com",
                            Name = "Barney Stinson",
                            PhoneNumber = "00000004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "robin.scherbatsky@himym.com",
                            Name = "Robin Scherbatsky",
                            PhoneNumber = "00000005"
                        });
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Booking", b =>
                {
                    b.HasOne("BookingApp.Models.Domain.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApp.Models.Domain.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Room", b =>
                {
                    b.HasOne("BookingApp.Models.Domain.Office", "Office")
                        .WithMany("Rooms")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Seat", b =>
                {
                    b.HasOne("BookingApp.Models.Domain.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Office", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Room", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.Seat", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookingApp.Models.Domain.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
